apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: postgres-project
  namespace: argocd
spec:
  description: Stateful PostgreSQL Database Project in MicroK8s
  sourceRepos:
    - https://charts.bitnami.com/bitnami
  destinations:
    - namespace: database
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
