# service-3.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service3
  template:
    metadata:
      labels:
        app: service3
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - name: http
              containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: service3
  labels:
    app: svc-service3
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: service3
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: ilb-cluster-service
  #namespace: ing-test-ns
spec:
  selector:
    #name: service3
    app: svc-service3
  type: LoadBalancer
  loadBalancerIP: 192.168.29.65
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443